services:
  todoapp:
    container_name: todoapp
    image: thanhdt05/todoapp:1.0.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    working_dir: /var/www/html/frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
      - frontend_node_modules:/var/www/html/frontend/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - todoapp

  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  frontend_node_modules: