services:
  todoapp:
    container_name: todoapp
    image: thanhdt05/todoapp:1.0.1
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  queue:
    build: .
    working_dir: /var/www/html
    command: php artisan horizon
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  scheduler:
    build: .
    working_dir: /var/www/html
    command: php artisan schedule:work
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: todoapp_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: todoapp_mailpit
    ports:
      - '8025:8025' # Web UI
      - '1025:1025' # SMTP Port

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html/frontend
    ports:
      - '5173:5173'
    volumes:
      - .:/var/www/html
      - frontend_node_modules:/var/www/html/frontend/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - todoapp

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U todo -d todo_app']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  redis_data:
  frontend_node_modules:
